CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,

  name VARCHAR(60) NOT NULL UNIQUE,
  email VARCHAR(120) UNIQUE,
  password VARCHAR(120),
  status BOOLEAN DEFAULT false,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6),
  deleted_at TIMESTAMP
);
